# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
name: pkgdown

on:
  push:
    branches: [website]
  pull_request:
    branches: [website]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:

      - name: Checkout repo for workflow access
        uses: actions/checkout@v3

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@v2

      - name: Setup R environment
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Set up dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        env:
          _R_CHECK_FORCE_SUGGESTS: false
          _R_CHECK_RD_XREFS: false
        with:
          dependencies: '"hard"' # do not use suggested dependencies
          extra-packages: any::pkgdown, any::utils, local::.
          needs: website

      - name: Set up dependencies (GiottoData)
        run: |
          new_github_ver_avail <- function(
              url, current_ver = NULL
          ) {
            # Return NULL if any warnings or errors due to inaccessible
            descfile <- tryCatch(
                expr = readLines(url),
                warning = function(w) NULL,
                error = function(e) NULL
            )
            # silently return NULL if not found
            if (is.null(descfile)) return(invisible())

            # parse github version number
            gh_ver <- descfile[grep(pattern = "Version:", descfile)]
            gh_ver <- gsub(pattern = "Version: ", replacement = "", gh_ver)
            # see if GH version is newer
            ver_compare <- utils::compareVersion(gh_ver, as.character(current_ver))

            # silently return NULL if not newer
            if (ver_compare != 1) return(invisible())

            # return newer version number
            return(gh_ver)
          }

          new_gdata <- new_github_ver_avail(
            url = "https://raw.githubusercontent.com/drieslab/GiottoData/master/DESCRIPTION",
            current_ver = packageVersion("GiottoData")
          )

          suppressWarnings({
            if (!is.null(new_gdata))
            remotes::install_github('drieslab/GiottoData', build = FALSE)
          })
        shell: Rscript {0}

      - name: Build site
        run: pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)
        shell: Rscript {0}

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          clean: false
          branch: gh-pages
          folder: docs
